
##################################################
# 🔐 PortOne V2 결제 검증용 (서버)
##################################################

# V2 API Secret (식별코드 · API Keys → V2 API에서 발급)
portone.v2.api-secret=r2LQ7FqkcOtCEhjAOdKosUo1mJLatlhuDLr6gJ4bERx0mWlWjGFB7tDWqWel74j9rZuD37A0hAJQs8uN


##################################################
# 💳 PortOne 프론트 초기화용 (선택)
##################################################

# 가맹점 식별코드 (IMP.init 에 사용)
portone.imp.id=imp06217828