# \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uBE44\uBC00\uBC88\uD638
spring.datasource.password=1234

# OAuth2 \uCE74\uCE74\uC624 \uBE44\uBC00 \uC815\uBCF4
spring.security.oauth2.client.registration.kakao.client-id=874b314c87bd282a0613ba2a3997f5bc
spring.security.oauth2.client.registration.kakao.client-secret=QMyCqnnWtha7rJBibErgwJ61bR5HzK0z

# Gmail \uC571 \uBE44\uBC00\uBC88\uD638 (\uC774\uBBF8 \uB178\uCD9C\uB418\uC5C8\uC73C\uB2C8 \uAF2D \uC7AC\uBC1C\uAE09 \uBC1B\uC73C\uC138\uC694!)
spring.mail.password=aulc kktd xcpr egqa

# PortOne Channel Keys
portone.imp.id=imp06217828
portone.channel.kakao=channel-key-37e73800-4d4e-45c6-b48e-73133dbaee29
portone.channel.toss=channel-key-208b6533-848c-4fd4-83b3-0590b86ef4c0
portone.channel.naver=channel-key-e64f15df-20b8-4b98-b80e-142f114773e6
portone.channel.card=channel-key-95ebcbee-1000-43a5-884e-0d2173d27a37