# secret 프로필을 활성화하여 application-secret.properties를 읽어옴
spring.profiles.active=secret

spring.application.name=culti

server.port=80

spring.datasource.url=jdbc:mysql://localhost:3306/culti_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
spring.datasource.username=culti
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false



# OAuth2 Client Registration (ìë¹ì¤ ì ë³´)

# OAuth2 Client Registration (서비스 정보)
<<<<<<< HEAD

spring.security.oauth2.client.registration.kakao.client-id=874b314c87bd282a0613ba2a3997f5bc
spring.security.oauth2.client.registration.kakao.client-secret=QMyCqnnWtha7rJBibErgwJ61bR5HzK0z
=======
spring.security.oauth2.client.registration.kakao.client-id=
spring.security.oauth2.client.registration.kakao.client-secret=
>>>>>>> branch 'feature/bookingstore' of https://github.com/yuj-2/culti-project.git
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:80/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.client-name=Kakao
spring.security.oauth2.client.registration.kakao.scope=profile_nickname

# OAuth2 Provider (ì¹´ì¹´ì¤ API ìëí¬ì¸í¸)

kakao.api.js-key=b32f0cea9b46043cd332b797ceefc593

# OAuth2 Provider (카카오 API 엔드포인트)

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id



# ë©ì¼ ìë² í¸ì¤í¸ (êµ¬ê¸)
spring.mail.host=smtp.gmail.com
# í¬í¸ ë²í¸ (TLS ë°©ìì 587)
spring.mail.port=587
# ë³¸ì¸ì êµ¬ê¸ ì´ë©ì¼ ê³ì 
spring.mail.username=sykimhoyeon@gmail.com
<<<<<<< HEAD
=======
# 구글에서 발급받은 16자리 앱 비밀번호 (공백 없이 입력)
spring.mail.password=
>>>>>>> branch 'feature/bookingstore' of https://github.com/yuj-2/culti-project.git

# êµ¬ê¸ìì ë°ê¸ë°ì 16ìë¦¬ ì± ë¹ë°ë²í¸ (ê³µë°± ìì´ ìë ¥)

# 구글에서 발급받은 16자리 앱 비밀번호 (공백 없이 입력)
>>>>>>> refs/heads/main
spring.mail.password=dxnr qbuo pxaq oxyh

# SMTP ë³´ì ë° ì¸ì¦ ì¤ì 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.starttls.enable=true
